name: Build and Upload DB Binaries to R2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        include:
          # MongoDB
          - database: mongodb
            db_version: 8.0.0
            os: macos-latest
            platform: macos
            arch: arm64
            ext: tar.gz
          - database: mongodb
            db_version: 8.0.0
            os: macos-latest
            platform: macos
            arch: _x86_64
            ext: tar.gz
          - database: mongodb
            db_version: 8.0.0
            os: ubuntu-latest
            platform: linux
            arch: _x86_64
            ext: tar.gz

          # PostgreSQL
          - database: postgresql
            db_version: 16.0
            os: macos-latest
            platform: macos
            arch: arm64
            ext: tar.gz
          - database: postgresql
            db_version: 16.0
            os: macos-latest
            platform: macos
            arch: _x86_64
            ext: tar.gz
          - database: postgresql
            db_version: 16.0
            os: ubuntu-latest
            platform: linux
            arch: _x86_64
            ext: tar.gz

          # Redis
          - database: redis
            db_version: 7.0.15
            os: macos-latest
            platform: macos
            arch: arm64
            ext: tar.gz
          - database: redis
            db_version: 7.0.15
            os: macos-latest
            platform: macos
            arch: _x86_64
            ext: tar.gz
          - database: redis
            db_version: 7.0.15
            os: ubuntu-latest
            platform: linux
            arch: _x86_64
            ext: tar.gz

    environment: production

    env:
      R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
      R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      R2_BUCKET: ${{ secrets.R2_BUCKET }}
      R2_ENDPOINT: ${{ secrets.R2_ENDPOINT }}
      MACOS_IDENTITY: ${{ secrets.MACOS_IDENTITY }}
      MACOS_CERT_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
      MACOS_CERT_P12_BASE64: ${{ secrets.MACOS_CERT_P12_BASE64 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set environment variables
        shell: bash
        run: |
          echo "DATABASE=${{ matrix.database }}" >> $GITHUB_ENV
          echo "DB_VERSION=${{ matrix.db_version }}" >> $GITHUB_ENV
          echo "DB_MAJOR_VERSION=$(echo '${{ matrix.db_version }}' | cut -d. -f1)" >> $GITHUB_ENV
          echo "ARCH_CLEAN=$(echo '${{ matrix.arch }}' | sed 's/^_//')" >> $GITHUB_ENV

      - name: Set up architecture switching (x86_64 on macOS)
        if: matrix.arch == '_x86_64' && matrix.platform == 'macos'
        run: echo "alias brew='arch -x86_64 /usr/local/bin/brew'" >> $GITHUB_ENV

      - name: Install dependencies and fetch binaries
        shell: bash
        run: |
          mkdir -p ./raw/${DATABASE}/${DB_MAJOR_VERSION}/${{ matrix.platform }}/${{ matrix.arch }}

          case "$DATABASE" in
            redis)
              if [[ "$RUNNER_OS" == "macOS" ]]; then
                brew install redis
                cp $(brew --prefix redis)/bin/redis-server ./raw/${DATABASE}/${DB_MAJOR_VERSION}/${{ matrix.platform }}/${{ matrix.arch }}/
              else
                sudo apt update && sudo apt install redis-server -y
                cp $(which redis-server) ./raw/${DATABASE}/${DB_MAJOR_VERSION}/${{ matrix.platform }}/${{ matrix.arch }}/
              fi
              ;;
            mongodb)
              if [[ "$RUNNER_OS" == "macOS" ]]; then
                curl -LO https://fastdl.mongodb.org/osx/mongodb-macos-${ARCH_CLEAN}-${DB_VERSION}.tgz
                tar -xzf mongodb-macos-${ARCH_CLEAN}-${DB_VERSION}.tgz
                cp ./mongodb-*/bin/* ./raw/${DATABASE}/${DB_MAJOR_VERSION}/${{ matrix.platform }}/${{ matrix.arch }}/
              else
                curl -LO https://fastdl.mongodb.org/linux/mongodb-linux-x86_64-ubuntu2204-${DB_VERSION}.tgz
                tar -xzf mongodb-linux-x86_64-ubuntu2204-${DB_VERSION}.tgz
                cp ./mongodb-*/bin/* ./raw/${DATABASE}/${DB_MAJOR_VERSION}/${{ matrix.platform }}/${{ matrix.arch }}/
              fi
              ;;
            postgresql)
              if [[ "$RUNNER_OS" == "macOS" ]]; then
                brew install postgresql@${DB_MAJOR_VERSION}
                cp $(brew --prefix postgresql@${DB_MAJOR_VERSION})/bin/* ./raw/${DATABASE}/${DB_MAJOR_VERSION}/${{ matrix.platform }}/${{ matrix.arch }}/
              else
                sudo apt update && sudo apt install postgresql-${DB_MAJOR_VERSION} -y || sudo apt install postgresql -y
                cp /usr/lib/postgresql/${DB_MAJOR_VERSION}/bin/* ./raw/${DATABASE}/${DB_MAJOR_VERSION}/${{ matrix.platform }}/${{ matrix.arch }}/ || cp /usr/lib/postgresql/*/bin/* ./raw/${DATABASE}/${DB_MAJOR_VERSION}/${{ matrix.platform }}/${{ matrix.arch }}/
              fi
              ;;
          esac

      - name: Sign binaries on macOS
        if: runner.os == 'macOS'
        shell: bash
        run: |
          echo "$MACOS_CERT_P12_BASE64" | base64 --decode > certificate.p12

          security create-keychain -p temp temp.keychain
          security default-keychain -s temp.keychain
          security unlock-keychain -p temp temp.keychain

          security import certificate.p12 -k temp.keychain -P "$MACOS_CERT_PASSWORD" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k temp temp.keychain

          echo "Signing binaries in ./raw/${DATABASE}/${DB_MAJOR_VERSION}/${{ matrix.platform }}/${{ matrix.arch }}..."

          for file in ./raw/${DATABASE}/${DB_MAJOR_VERSION}/${{ matrix.platform }}/${{ matrix.arch }}/*; do
            if [[ -x "$file" && ! -d "$file" ]]; then
              echo "Signing $file"
              codesign --force --options runtime --timestamp --sign "$MACOS_IDENTITY" "$file"
            fi
          done

      - name: Archive binaries into platform-specific package
        shell: bash
        run: |
          mkdir -p ./packages/${DATABASE}/${DB_MAJOR_VERSION}/${{ matrix.platform }}
          tar -czf ./packages/${DATABASE}/${DB_MAJOR_VERSION}/${{ matrix.platform }}/${{ matrix.arch }}.tar.gz -C ./raw/${DATABASE}/${DB_MAJOR_VERSION}/${{ matrix.platform }}/${{ matrix.arch }} .

      - name: Upload to R2 with aws-cli
        shell: bash
        run: |
          set -euo pipefail
          pip install awscli --break-system-packages

          if [[ -z "$R2_ENDPOINT" ]]; then
            echo "R2_ENDPOINT is empty. Skipping upload."
            exit 1
          fi

          export AWS_ACCESS_KEY_ID="$R2_ACCESS_KEY_ID"
          export AWS_SECRET_ACCESS_KEY="$R2_SECRET_ACCESS_KEY"
          export AWS_DEFAULT_REGION="auto"

          aws s3 cp \
            ./packages/${DATABASE}/${DB_MAJOR_VERSION}/${{ matrix.platform }}/ \
            s3://$R2_BUCKET/${DATABASE}/${DB_MAJOR_VERSION}/${{ matrix.platform }}/ \
            --recursive \
            --endpoint-url "$R2_ENDPOINT"
